project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!posts/slides/"

website:
  title: "Jason Bryer, Ph.D."
  site-url: https://jbryer.github.io/portfoliotalk
  description: "Sample portfolio website"
  open-graph:
    locale: en_US
  twitter-card:
    creator: "@jbryer"
  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: "Projects"
        href: projects.html
      - text: "Blog"
        href: blog.html
      - icon: rss
        href: blog.xml
  page-footer:
    left: "Site created with Quarto by Jason Bryer."

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



